steps:
  install:
    image: node:20-alpine
    commands:
      - npm ci
    when:
      - event: [push, pull_request, tag, manual]

  typecheck:
    image: node:20-alpine
    commands:
      - npx tsc --noEmit
    depends_on:
      - install
    when:
      - event: [push, pull_request, tag, manual]

  build:
    image: node:20-alpine
    commands:
      - npx tsc -p tsconfig.json
    depends_on:
      - typecheck
    when:
      - event: [push, pull_request, tag, manual]

  docker-build:
    image: woodpeckerci/plugin-docker-buildx:4
    settings:
      repo: sparkfn/webhook-listener
      dockerfile: Dockerfile
      dry_run: true
    depends_on:
      - build
    when:
      - event: push
        branch: [main, prod]

  notify-failure:
    image: alpine:latest
    commands:
      - echo "Pipeline failed for ${CI_REPO} on branch ${CI_COMMIT_BRANCH}"
      - echo "Commit ${CI_COMMIT_SHA} by ${CI_COMMIT_AUTHOR}"
      - echo "Check pipeline at ${CI_PIPELINE_FORGE_URL}"
    depends_on:
      - build
    when:
      - event: [push, pull_request, tag, manual]
        status: failure
